name: ci-node-pipeline-sonar-cloud
on:
  push:
    branches: [ main ]
jobs:
  check-application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install jest @types/jest sonar-scanner --only-dev    
      - run: npm run test
      - run: npm start
